import fs from "node:fs";
import { ConfigStore } from "../config/config-store";
import { expandTilde } from "@/utils/platform";

export class SshConfigGenerator {
  private store: ConfigStore;

  constructor(store: ConfigStore) {
    this.store = store;
  }

  generate(): string {
    this.store.ensureDirectories();
    const accounts = this.store.loadAccounts();
    const paths = this.store.getPathResolver();
    const generatedSshFile = paths.getGeneratedSshConfigFile();

    let content = `# Auto-generated by GitBridge. DO NOT EDIT DIRECTLY.\n`;
    content += `# Generated at: ${new Date().toISOString()}\n\n`;

    // Filter accounts with SSH key configured
    const sshAccounts = accounts.filter((a) => a.sshKeyPath);

    if (sshAccounts.length === 0) {
      content += `# No accounts currently configured with custom SSH keys.\n`;
    } else {
      for (const account of sshAccounts) {
        const hostAlias = `${account.host}-${account.id}`;
        const keyPath = expandTilde(account.sshKeyPath!);

        content += `# Account: ${account.displayName || account.username} (${account.providerId})\n`;
        content += `Host ${hostAlias}\n`;
        content += `    HostName ${account.host}\n`;
        content += `    User git\n`;
        if (account.sshPort) {
          content += `    Port ${account.sshPort}\n`;
        }
        content += `    IdentityFile ${keyPath}\n`;
        content += `    IdentitiesOnly yes\n\n`;
      }
    }

    fs.writeFileSync(generatedSshFile, content, { encoding: "utf-8", mode: 0o600 });
    return generatedSshFile;
  }
}
