import type { CredentialStore } from "./credential-store";
import { CredentialStoreError } from "@/utils/errors";
import { execProcess } from "@/utils/proc";

/**
 * `security -i` reads commands from stdin with a whitespace tokenizer, so the
 * account and service names we pass must be plain tokens. Account ids are
 * generated by GitBridge and services are hostnames (with optional port).
 */
function isSafeKeychainToken(value: string): boolean {
  return /^[A-Za-z0-9._:@-]+$/.test(value);
}

export class MacOSKeychainCredentialStore implements CredentialStore {
  readonly name = "macOS Keychain";

  async isAvailable(): Promise<boolean> {
    if (process.platform !== "darwin") return false;
    try {
      const res = await execProcess("which", ["security"], { allowFailure: true });
      return res.exitCode === 0;
    } catch {
      return false;
    }
  }

  async set(service: string, account: string, secret: string): Promise<void> {
    try {
      if (!isSafeKeychainToken(service) || !isSafeKeychainToken(account)) {
        throw new Error(`Keychain service/account must be plain tokens (got '${service}' / '${account}')`);
      }

      await this.delete(service, account);

      // Feed the command to `security -i` over stdin so the secret (even
      // hex-encoded) never appears in the process arguments, which `ps` shows
      // to every user on the machine. Hex keeps the value a single token for
      // the interactive parser.
      const hex = Buffer.from(secret, "utf8").toString("hex");
      await execProcess("security", ["-i"], {
        stdin: `add-generic-password -a ${account} -s ${service} -X ${hex} -U\n`,
        allowFailure: true,
      });

      // Interactive mode does not reliably report a failed command in its exit
      // status, so confirm the item is really there before claiming success.
      const stored = await this.get(service, account);
      if (stored !== secret) {
        throw new Error("Keychain did not store the secret (read-back mismatch)");
      }
    } catch (err: unknown) {
      throw new CredentialStoreError(
        `Failed to store credential in macOS Keychain: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  async get(service: string, account: string): Promise<string | null> {
    try {
      const res = await execProcess(
        "security",
        ["find-generic-password", "-a", account, "-s", service, "-w"],
        { allowFailure: true }
      );

      if (res.exitCode === 0 && res.stdout.trim().length > 0) {
        return res.stdout.trim();
      }
      return null;
    } catch {
      return null;
    }
  }

  async delete(service: string, account: string): Promise<void> {
    try {
      await execProcess(
        "security",
        ["delete-generic-password", "-a", account, "-s", service],
        { allowFailure: true }
      );
    } catch {
      // ignore
    }
  }
}
