import fs from "node:fs";
import { ConfigStore } from "../config/config-store";
import { expandTilde } from "@/utils/platform";

export class GitConfigGenerator {
  private store: ConfigStore;

  constructor(store: ConfigStore) {
    this.store = store;
  }

  /**
   * Generates all Git configuration files into ~/.gitbridge/generated/
   */
  generate(): { mainConfigPath: string; generatedRules: string[] } {
    this.store.ensureDirectories();
    const config = this.store.loadConfig();
    const identities = this.store.loadIdentities();
    const accounts = this.store.loadAccounts();
    const paths = this.store.getPathResolver();

    const defaultIdentity = identities.find((i) => i.id === config.defaultIdentityId) || identities.find((i) => i.isDefault) || identities[0];

    const ruleFiles: string[] = [];

    // 1. Generate individual rule files
    for (const rule of config.rules) {
      const ruleIdentity = identities.find((i) => i.id === rule.identityId);
      const ruleFile = paths.getRuleGitConfigFile(rule.id);

      let ruleContent = `# Managed by GitBridge for rule: ${rule.id}\n`;
      if (ruleIdentity) {
        ruleContent += `[user]\n`;
        ruleContent += `    name = ${ruleIdentity.name}\n`;
        ruleContent += `    email = ${ruleIdentity.email}\n`;
        if (ruleIdentity.signingKey) {
          ruleContent += `    signingkey = ${ruleIdentity.signingKey}\n`;
          ruleContent += `    # format = ssh or gpg\n`;
        }
      }

      // Check if rule specifies an account with SSH rewrite
      if (rule.defaultAccountId) {
        const account = accounts.find((a) => a.id === rule.defaultAccountId);
        if (account && account.host) {
          const aliasHost = `${account.host}-${account.id}`;
          // e.g. insteadOf = git@github.com:
          ruleContent += `\n[url "git@${aliasHost}:"]\n`;
          ruleContent += `    insteadOf = git@${account.host}:\n`;
        }
      }

      fs.writeFileSync(ruleFile, ruleContent, { encoding: "utf-8", mode: 0o644 });
      ruleFiles.push(ruleFile);
    }

    // 2. Generate main.gitconfig
    let mainContent = `# Auto-generated by GitBridge. DO NOT EDIT DIRECTLY.\n`;
    mainContent += `# Generated at: ${new Date().toISOString()}\n\n`;

    if (defaultIdentity) {
      mainContent += `# Default Identity\n`;
      mainContent += `[user]\n`;
      mainContent += `    name = ${defaultIdentity.name}\n`;
      mainContent += `    email = ${defaultIdentity.email}\n`;
      if (defaultIdentity.signingKey) {
        mainContent += `    signingkey = ${defaultIdentity.signingKey}\n`;
      }
      mainContent += `\n`;
    }

    if (config.settings.credentialHelperEnabled) {
      mainContent += `# Git Credential Helper Bridge\n`;
      mainContent += `[credential]\n`;
      mainContent += `    helper = gitbridge credential\n\n`;
    }

    if (config.rules.length > 0) {
      mainContent += `# Directory-Based Conditional Includes\n`;
      for (const rule of config.rules) {
        const ruleFile = paths.getRuleGitConfigFile(rule.id);
        const expandedRulePath = expandTilde(rule.path);
        // gitdir format requires trailing slash for directories
        const gitDirPattern = expandedRulePath.endsWith("/") ? `${expandedRulePath}**` : `${expandedRulePath}/**`;
        mainContent += `[includeIf "gitdir:${gitDirPattern}"]\n`;
        mainContent += `    path = ${ruleFile}\n\n`;
      }
    }

    const mainFile = paths.getMainGitConfigFile();
    fs.writeFileSync(mainFile, mainContent, { encoding: "utf-8", mode: 0o644 });

    return {
      mainConfigPath: mainFile,
      generatedRules: ruleFiles,
    };
  }
}
